//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudManagerUI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloudManager
    {
        public string File_ID { get; set; }
        public string Cloud_ID { get; set; }
        public string File_Name { get; set; }
        public string File_Path { get; set; }
        public Nullable<System.DateTime> File_LastChanged { get; set; }
        public bool File_IsDeleted { get; set; }
        public bool IsFolder { get; set; }
        public bool File_IsInRoot { get; set; }
        public string RootFolderPath { get; set; }
        public string Cloud_Path { get; set; }
    }
}
